In [5]:
# import libraries 
import pandas as pd
import numpy as np
from dateutil import parser
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [6]:
pd.set_option('display.float', lambda x: f'{x:.2f}')

Month4:
Week 3:

Assignment: Nigeria Jiji Housing Marketplace Data Analysis
Title:
Market Analysis of Housing Sales on Jiji.ng Using Python
Overview
You will analyze real-world housing listings from the Jiji Nigeria Marketplace.
Your task is to extract listing data using Python from Jiji’s public API, clean and preprocess the data, perform exploratory data analysis (EDA), visualize the trends, and generate business insights and recommendations.
This assignment will help you practice:
Working with APIs


JSON data extraction


Data cleaning and transformation


Exploratory data analysis


Visualization


Business insight generation



Task 1: Data Extraction
Objective:
Extract housing data from the Jiji API and convert it into a clean DataFrame.
API Endpoint to Use:
https://jiji.ng/api_web/v1/listing?slug=houses-apartments-for-sale&page=1&webp=true

Requirements:
Write a Python script to send a GET request to the endpoint.


Use the requests library.


Extract the following key fields from each advert object:


title


region, region_name, region_parent_name


price_title (formatted price)


attrs fields


Property size


Bedrooms


Bathrooms


Furnishing status


is_boost (enterprise/diamond)


Convert the extracted data into a Pandas DataFrame.


Save the dataset locally as jiji_housing_raw.csv.



Task 2: Data Cleaning
Objective:
Prepare the dataset for reliable analysis.
Questions to Guide Cleaning:
Missing Values


Which columns have missing values?


How will you handle missing property size, bedrooms, bathrooms, or furnishing?


Price Cleaning


Convert the price from strings like “₦ 85,500,000” to float (85500000.00)


Are there outlier prices that should be removed?


Categorical Cleaning


Standardize region, region_name, region_parent_name.


Convert furnishing type to consistent categories
 (e.g., Furnished / Semi-furnished / Unfurnished / Unknown)


Attributes Extraction


Extract values for Bedrooms, Bathrooms, Property size from the attrs JSON list.


Remove duplicates


Look for duplicate titles or identical rows.


Save cleaned dataset as:
 jiji_housing_cleaned.csv



Task 3: Exploratory Data Analysis (EDA)
Objective:
Understand the structure, patterns, and distribution of the Nigerian housing marketplace on Jiji.
Your EDA Should Answer These Questions:
Price Analysis


What is the average house price in Nigeria?


Which state has the highest and lowest mean property price?


Property Size & Features


What is the distribution of property sizes?


Do houses with more bedrooms/bathrooms cost significantly more?


Regional Trends


Which regions have the highest number of listings?


Which regions dominate premium property sales?


Furnishing Analysis


Are furnished apartments more expensive on average?


Listing Type


Do boosted/enterprise listings have higher prices?



Task 4 — Visualization
Create the following visualizations (using Streamlit):
KPI SECTION (Top of Dashboard)
Q1. How many houses are listed in the dataset?
 Display the total number of house listings as a KPI.
Q2. What is the average price of houses in Nigeria?
Display the mean house price (₦) as a KPI.
Q3. Which house region appears most frequently in the listings?
 Display the most common house region as a KPI.
Q4. What percentage of houses are furnished?
 Display the percentage of furnished houses as a KPI.

Required Charts:
Bar Chart: Number of listings per state


Bar Chart: Average price per state


Histogram: Distribution of property prices


Boxplot: Price by number of bedrooms


Scatter Plot: Property size vs. price


Pie Chart: Furnishing type distribution


Heatmap: Correlation of numeric variables (price, size, bedrooms, bathrooms)


Use:
Matplotlib


Seaborn


Plotly



Task 5: Summary of Findings 
Rewrite your findings by answering the following:
Which states have the highest-priced listings?


Which states are the most affordable?


Do furnished homes consistently cost more than unfurnished ones?


How strongly do bedrooms, bathrooms, or property size influence price?


Are boosted (Enterprise) listings typically more expensive?


What property types attract premium pricing?


What patterns exist in Lagos vs Abuja vs other regions?


Your summary should be 6–10 lines.

Task 6: Business Insights & Recommendations
Provide a 5–7 line business-focused insight summary, answering:
Which housing type or feature performs best overall on Jiji?


Which state contributes the most revenue potential?


Which states underperform?


Which period (if using timestamps) records the highest listing activity?


What strategies can improve sales in low-performing regions?


What can sellers do to increase listing visibility and pricing power?



Final Deliverables
Upload the following:
Python notebook (.ipynb)


Raw dataset (CSV)


Cleaned dataset (CSV)


Visualizations (inside notebook)


Insight & recommendation section

In [7]:
# Load a csv file on pandas
#Load csv file dataset on pandas 

df = pd.read_csv("data/jiji_housing_raw.csv")

df

,title,property_size,bedrooms,bathrooms,furnishing,region,region_name,region_parent_name,is_boost,price
0,"3bdrm Bungalow in Greenleaf Estate, Ebute for ...",300.00,3,4,unfurnished,"Ikorodu, Ebute",Ebute,Ikorodu,premium,"₦ 43,000,000"
1,Furnished 4bdrm Duplex in Enugu for sale,1000.00,4,4,furnished,"Enugu State, Enugu",Enugu,Enugu State,premium,"₦ 350,000,000"
2,"5bdrm Duplex in Basic Estate, Lokogoma for sale",600.00,5,4,unfurnished,"Abuja (FCT), Lokogoma",Lokogoma,Abuja (FCT),diamond,"₦ 220,000,000"
3,2bdrm Apartment in Lekki Phase 1 for sale,300.00,2,2,semi-furnished,"Lekki, Lekki Phase 1",Lekki Phase 1,Lekki,vip_gold,"₦ 350,000,000"
4,2bdrm Bungalow in Ewekoro for sale,600.00,2,2,unfurnished,"Ogun State, Ewekoro",Ewekoro,Ogun State,False,"₦ 7,000,000"
...,...,...,...,...,...,...,...,...,...,...
1994,7bdrm Duplex in Kado for sale,320.00,7,8,unfurnished,"Abuja (FCT), Kado",Kado,Abuja (FCT),diamond,"₦ 1,600,000,000"
1995,4bdrm Duplex in Gaduwa for sale,400.00,4,6,semi-furnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),diamond,"₦ 250,000,000"
1996,6bdrm Bungalow in New London Estate for sale,620.00,6,6,unfurnished,"Ipaja, Baruwa",Baruwa,Ipaja,diamond,"₦ 65,000,000"
1997,4bdrm Duplex in Wuye for sale,150.00,4,5,semi-furnished,"Abuja (FCT), Wuye",Wuye,Abuja (FCT),diamond,"₦ 500,000,000"
1998,4bdrm Duplex in Jahi for sale,250.00,4,5,unfurnished,"Abuja (FCT), Jahi",Jahi,Abuja (FCT),diamond,"₦ 250,000,000"

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               1999 non-null   str
 1   property_size       1993 non-null   float64
 2   bedrooms            1999 non-null   int64
 3   bathrooms           1999 non-null   int64
 4   furnishing          1999 non-null   str
 5   region              1999 non-null   str
 6   region_name         1999 non-null   str
 7   region_parent_name  1998 non-null   str
 8   is_boost            1999 non-null   str
 9   price               1999 non-null   str
dtypes: float64(1), int64(2), str(7)
memory usage: 379.2 KB

In [9]:
#Missing Values

df.isnull().sum()

title                 0
property_size         6
bedrooms              0
bathrooms             0
furnishing            0
region                0
region_name           0
region_parent_name    1
is_boost              0
price                 0
dtype: int64

In [10]:
# I dropped all the null values in the dataset since its just 4 data out of 2000 dataset. 

df.dropna(inplace=True)

# Rechecking the null values in the dataset

df.isnull().sum()

title                 0
property_size         0
bedrooms              0
bathrooms             0
furnishing            0
region                0
region_name           0
region_parent_name    0
is_boost              0
price                 0
dtype: int64

In [11]:
df.shape

(1992, 10)

In [12]:
df.columns

Index(['title', 'property_size', 'bedrooms', 'bathrooms', 'furnishing',
       'region', 'region_name', 'region_parent_name', 'is_boost', 'price'],
      dtype='str')

In [13]:
#Data cleaning 
#Question: Standardize region, region_name, region_parent_name.

df.rename(columns={
    "title" : "Title" , 
    "property_size" : "Property Size" ,
    "bedrooms" : "Bedrooms" ,
    "bathrooms" : "Bathrooms" ,
    "furnishing" : "Furnishing" ,
    "region" : "Region" ,
    "region_name" : "Region Name" ,
    "region_parent_name" : "Region Parent Name",
    "is_boost" : "Is Boost",
    "price" : "Price"
} , inplace=True)

df.head(3)

,Title,Property Size,Bedrooms,Bathrooms,Furnishing,Region,Region Name,Region Parent Name,Is Boost,Price
0,"3bdrm Bungalow in Greenleaf Estate, Ebute for ...",300.00,3,4,unfurnished,"Ikorodu, Ebute",Ebute,Ikorodu,premium,"₦ 43,000,000"
1,Furnished 4bdrm Duplex in Enugu for sale,1000.00,4,4,furnished,"Enugu State, Enugu",Enugu,Enugu State,premium,"₦ 350,000,000"
2,"5bdrm Duplex in Basic Estate, Lokogoma for sale",600.00,5,4,unfurnished,"Abuja (FCT), Lokogoma",Lokogoma,Abuja (FCT),diamond,"₦ 220,000,000"

In [14]:
#check for unique values in each colunms

print(df["Title"].unique())
print(df["Property Size"].unique())
print(df["Bedrooms"].unique())
print(df["Bathrooms"].unique())
print(df["Furnishing"].unique())
print(df["Region"].unique())
print(df["Region Name"].unique())
print(df["Region Parent Name"].unique())
print(df["Is Boost"].unique())
print(df["Price"].unique())

<ArrowStringArray>
[          '3bdrm Bungalow in Greenleaf Estate, Ebute for sale',
                     'Furnished 4bdrm Duplex in Enugu for sale',
              '5bdrm Duplex in Basic Estate, Lokogoma for sale',
                    '2bdrm Apartment in Lekki Phase 1 for sale',
                           '2bdrm Bungalow in Ewekoro for sale',
                           '4bdrm Duplex in Sabo Yaba for sale',
                 'Furnished 5bdrm Duplex in Lekki Ph1 for sale',
                      'Furnished Mini Flat in Oluyole for sale',
                                  '2bdrm House in Ifo for sale',
                        '5bdrm Duplex in Osapa London for sale',
 ...
                            '3bdrm Apartment in Lekki for sale',
 '4bdrm Duplex in Admiral Estate Close, Akala Express for sale',
               '4bdrm Duplex in Dss Quarters, Jericho for sale',
        'Furnished 5bdrm Duplex in Magodo Phase 2 Gra for sale',
                              '4bdrm Duplex in Guzape for sale',
                       '5bdrm Duplex in Zone 7 / Wuse for sale',
                                '7bdrm Duplex in Kado for sale',
                              '4bdrm Duplex in Gaduwa for sale',
                 '6bdrm Bungalow in New London Estate for sale',
                                '4bdrm Duplex in Wuye for sale']
Length: 1421, dtype: str
[ 300. 1000.  600.  500.  150.  400. 1800.  650.  250. 1500.  200. 2159.
  550.  800. 3000.  442.  298.  350.  750. 2000.  648.  289.  100.  900.
  700.  675.   10.  579. 3500.  761. 4200.  450.  330.  465.  635.  640.
  630.  480.  930.  253.  530.  638. 1860.  280.  634. 1290. 1200.  775.
 4046.  620. 1360.  680.  232.  728.  920.  456. 4500.  627. 4000.  756.
 1566. 1345.  730. 1300.  777.  517. 1350.  570. 5000.  470.  325.  460.
  580.  420.  424.  310.  720.  430.  520.  632.  320. 1672.   50.  315.
 1600.  842. 2716. 2578.  111.   14.  210.  402.   88.  306.   41.   40.
  347.   30.  469.   60.   33.  270.   75.  603. 1346.  370.  378.  180.
  390.  713. 3400.  669.  560.  453.  540.  340.  230.   35.  760.  260.
  722.  120.  850.   90.  345. 2500.   80.  812.  989.  960. 1100.  130.
  918. 4501. 1700. 1050.  485.   95.   15.  986.  380. 1986.  220. 1022.
 3200.  817.  955. 1625. 1735.  125. 1320.  204.  248.  317.   12. 1020.
  114.  222.  333.  702. 2200. 4100.  190. 1982.  287.  290.  276.  279.
  360.  830.  312.  389.  546. 1470. 1400.  278.  656.  140. 4900. 1185.
 2074. 1492.  557. 1450.  284.  742.  383.  209.   25. 1180.  910. 1030.
  913.  950. 1150.  780.  739.  525.  463.  639.]
[ 3  4  5  2  8  6 17  7  9  1 10 12 20 16 18 15 13]
[ 4  2  5  3 16  1  6 17  7  8  9 12 20 10 18 15 13 14]
<ArrowStringArray>
['unfurnished', 'furnished', 'semi-furnished']
Length: 3, dtype: str
<ArrowStringArray>
[                 'Ikorodu, Ebute',              'Enugu State, Enugu',
           'Abuja (FCT), Lokogoma',            'Lekki, Lekki Phase 1',
             'Ogun State, Ewekoro',               'Yaba, Sabo / Yaba',
              'Oyo State, Oluyole',                 'Ogun State, Ifo',
             'Lekki, Osapa london',                 'Ibadan, Basorun',
 ...
                    'Ibadan, Ojoo',                'Ibadan, Omi Adio',
                   'Ibadan, Apata', 'Egbe/Idimu, Isheri / Egbe Idimu',
                  'Oyo State, Oyo',                  'Ibadan, Bodija',
      'Ikeja, Obafemi Awolowo Way',             'Wuse, Zone 2 / Wuse',
            'Abuja (FCT), Katampe',             'Wuse, Zone 7 / Wuse']
Length: 284, dtype: str
<ArrowStringArray>
[              'Ebute',               'Enugu',            'Lokogoma',
       'Lekki Phase 1',             'Ewekoro',         'Sabo / Yaba',
             'Oluyole',                 'Ifo',        'Osapa london',
             'Basorun',
 ...
                'Ojoo',            'Omi Adio',               'Apata',
 'Isheri / Egbe Idimu',                 'Oyo',              'Bodija',
 'Obafemi Awolowo Way',       'Zone 2 / Wuse',             'Katampe',
       'Zone 7 / Wuse']
Length: 283, dtype: str
<ArrowStringArray>
[           'Ikorodu',        'Enugu State',        'Abuja (FCT)',
              'Lekki',         'Ogun State',               'Yaba',
          'Oyo State',             'Ibadan',               'Ogba',
        'Lagos State',              'Ipaja',           'Maryland',
         'Egbe/Idimu',            'Katampe',             'Kosofe',
               'Ajah',    'Victoria Island',        'Kwara State',
                'Oyo',          'Edo State',              'Ikoyi',
           'Gwarinpa',              'Ibeju',             'Kabusa',
     'Lugbe District',       'Apo District',              'Ojodu',
         'Osun State',            'Gbagada',       'Rivers State',
      'Port-Harcourt',              'Ikeja', 'Lagos Island (Eko)',
              'Agege',             'Magodo',           'Alimosho',
              'Ogudu',             'Egbeda',              'Isolo',
      'Ikotun/Igando',          'Imo State',        'Delta State',
            'Shomolu',       'Amuwo-Odofin',              'Bwari',
       'Ifako-Ijaiye',         'Abia State',            'Garki 1',
           'Surulere',                'Epe',              'Ojota',
        'Ekiti State',             'Gwagwa',         'Ondo State',
             'Ejigbo',             'Sagamu',               'Jiwa',
               'Wuse',             'Oshodi']
Length: 59, dtype: str
<ArrowStringArray>
['premium', 'diamond', 'vip_gold', 'False', 'enterprise', 'basic', 'vip']
Length: 7, dtype: str
<ArrowStringArray>
[    '₦ 43,000,000',    '₦ 350,000,000',    '₦ 220,000,000',
      '₦ 7,000,000',    '₦ 300,000,000',  '₦ 1,200,000,000',
     '₦ 33,000,000',     '₦ 25,000,000',    '₦ 900,000,000',
    '₦ 420,000,000',
 ...
     '₦ 68,000,000',     '₦ 58,000,000',     '₦ 11,000,000',
     '₦ 82,000,000',     '₦ 67,000,000', '₦ 26,000,000,000',
     '₦ 42,000,000',  '₦ 4,900,000,000',    '₦ 855,000,000',
     '₦ 84,600,000']
Length: 228, dtype: str

In [15]:
# Price cleaning 
# Question: Convert the price from strings like “₦ 85,500,000” to float (85500000.00)

df["Price"] = (
    df["Price"]
    .astype(str)
    .str.replace("₦", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)
df["Price"]

0        43000000.00
1       350000000.00
2       220000000.00
3       350000000.00
4         7000000.00
            ...
1994   1600000000.00
1995    250000000.00
1996     65000000.00
1997    500000000.00
1998    250000000.00
Name: Price, Length: 1992, dtype: float64

In [16]:
#Are there outlier prices that should be removed?
#exclude an outliers in dataframe

Q1 = df['Price'].quantile(0.25)
Q3 = df['Price'].quantile(0.75)
Q1
Q3
IQR = Q3 -Q1
IQR

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = ( df['Price'] < lower_bound) | ( df['Price'] > upper_bound)

print(outliers.sum())

217

In [17]:
# Create a new df after removing price column outliers 

new_df = df[
    (df['Price'] > lower_bound) & ( df['Price'] < upper_bound)
] 

new_df

,Title,Property Size,Bedrooms,Bathrooms,Furnishing,Region,Region Name,Region Parent Name,Is Boost,Price
0,"3bdrm Bungalow in Greenleaf Estate, Ebute for ...",300.00,3,4,unfurnished,"Ikorodu, Ebute",Ebute,Ikorodu,premium,43000000.00
1,Furnished 4bdrm Duplex in Enugu for sale,1000.00,4,4,furnished,"Enugu State, Enugu",Enugu,Enugu State,premium,350000000.00
2,"5bdrm Duplex in Basic Estate, Lokogoma for sale",600.00,5,4,unfurnished,"Abuja (FCT), Lokogoma",Lokogoma,Abuja (FCT),diamond,220000000.00
3,2bdrm Apartment in Lekki Phase 1 for sale,300.00,2,2,semi-furnished,"Lekki, Lekki Phase 1",Lekki Phase 1,Lekki,vip_gold,350000000.00
4,2bdrm Bungalow in Ewekoro for sale,600.00,2,2,unfurnished,"Ogun State, Ewekoro",Ewekoro,Ogun State,False,7000000.00
...,...,...,...,...,...,...,...,...,...,...
1993,5bdrm Duplex in Zone 7 / Wuse for sale,300.00,5,6,semi-furnished,"Wuse, Zone 7 / Wuse",Zone 7 / Wuse,Wuse,diamond,750000000.00
1995,4bdrm Duplex in Gaduwa for sale,400.00,4,6,semi-furnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),diamond,250000000.00
1996,6bdrm Bungalow in New London Estate for sale,620.00,6,6,unfurnished,"Ipaja, Baruwa",Baruwa,Ipaja,diamond,65000000.00
1997,4bdrm Duplex in Wuye for sale,150.00,4,5,semi-furnished,"Abuja (FCT), Wuye",Wuye,Abuja (FCT),diamond,500000000.00
1998,4bdrm Duplex in Jahi for sale,250.00,4,5,unfurnished,"Abuja (FCT), Jahi",Jahi,Abuja (FCT),diamond,250000000.00

In [18]:
# Question: Convert furnishing type to consistent categories (e.g., Furnished / Semi-furnished / Unfurnished / Unknown)

new_df["Furnishing"] = (
    new_df["Furnishing"]
    .str.lower()
    .replace({
        "semi furnished": "Semi-Furnished",
        "furnished": "Furnished",
        "unfurnished": "Unfurnished"
    })
)

new_df

,Title,Property Size,Bedrooms,Bathrooms,Furnishing,Region,Region Name,Region Parent Name,Is Boost,Price
0,"3bdrm Bungalow in Greenleaf Estate, Ebute for ...",300.00,3,4,Unfurnished,"Ikorodu, Ebute",Ebute,Ikorodu,premium,43000000.00
1,Furnished 4bdrm Duplex in Enugu for sale,1000.00,4,4,Furnished,"Enugu State, Enugu",Enugu,Enugu State,premium,350000000.00
2,"5bdrm Duplex in Basic Estate, Lokogoma for sale",600.00,5,4,Unfurnished,"Abuja (FCT), Lokogoma",Lokogoma,Abuja (FCT),diamond,220000000.00
3,2bdrm Apartment in Lekki Phase 1 for sale,300.00,2,2,semi-furnished,"Lekki, Lekki Phase 1",Lekki Phase 1,Lekki,vip_gold,350000000.00
4,2bdrm Bungalow in Ewekoro for sale,600.00,2,2,Unfurnished,"Ogun State, Ewekoro",Ewekoro,Ogun State,False,7000000.00
...,...,...,...,...,...,...,...,...,...,...
1993,5bdrm Duplex in Zone 7 / Wuse for sale,300.00,5,6,semi-furnished,"Wuse, Zone 7 / Wuse",Zone 7 / Wuse,Wuse,diamond,750000000.00
1995,4bdrm Duplex in Gaduwa for sale,400.00,4,6,semi-furnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),diamond,250000000.00
1996,6bdrm Bungalow in New London Estate for sale,620.00,6,6,Unfurnished,"Ipaja, Baruwa",Baruwa,Ipaja,diamond,65000000.00
1997,4bdrm Duplex in Wuye for sale,150.00,4,5,semi-furnished,"Abuja (FCT), Wuye",Wuye,Abuja (FCT),diamond,500000000.00
1998,4bdrm Duplex in Jahi for sale,250.00,4,5,Unfurnished,"Abuja (FCT), Jahi",Jahi,Abuja (FCT),diamond,250000000.00

In [19]:
new_df["Region Parent Name"].unique()

<ArrowStringArray>
[           'Ikorodu',        'Enugu State',        'Abuja (FCT)',
              'Lekki',         'Ogun State',               'Yaba',
          'Oyo State',             'Ibadan',               'Ogba',
        'Lagos State',              'Ipaja',           'Maryland',
         'Egbe/Idimu',            'Katampe',             'Kosofe',
               'Ajah',        'Kwara State',                'Oyo',
          'Edo State',              'Ikoyi',           'Gwarinpa',
              'Ibeju',             'Kabusa',     'Lugbe District',
       'Apo District',              'Ojodu',         'Osun State',
            'Gbagada',       'Rivers State',      'Port-Harcourt',
              'Ikeja', 'Lagos Island (Eko)',              'Agege',
             'Magodo',           'Alimosho',              'Ogudu',
             'Egbeda',              'Isolo',      'Ikotun/Igando',
          'Imo State',        'Delta State',            'Shomolu',
       'Amuwo-Odofin',              'Bwari',       'Ifako-Ijaiye',
         'Abia State',            'Garki 1',           'Surulere',
    'Victoria Island',                'Epe',              'Ojota',
        'Ekiti State',             'Gwagwa',         'Ondo State',
             'Ejigbo',             'Sagamu',               'Jiwa',
             'Oshodi',               'Wuse']
Length: 59, dtype: str

In [20]:
new_df['Region Parent Name'] = new_df['Region Parent Name'].replace(['Ajah', 'Ibeju', 'Ikorodu', 'Magodo', 'Lekki', 'Delta State', 'Ikeja', 'Gbagada',
                                                                     'Ikotun/Igando', 'Ejigbo','Surulere', 'Isolo', 'Ojodu', 'Egbeda', 'Ogudu',
                                                                     'Maryland', 'Kosofe', 'Alimosho', 'Ikoyi', 'Egbe/Idimu', 'Agege', 'Ondo State',
                                                                     'Victoria Island', 'Ipaja', 'Amuwo-Odofin', 'Ogba', 'Lagos Island (Eko)','Oshodi',
                                                                     'Mushin', 'Shomolu', 'Ifako-Ijaiye','Ilupeju', 'Epe'], 'Lagos State')

new_df['Region Parent Name'].unique()

<ArrowStringArray>
[   'Lagos State',    'Enugu State',    'Abuja (FCT)',     'Ogun State',
           'Yaba',      'Oyo State',         'Ibadan',        'Katampe',
    'Kwara State',            'Oyo',      'Edo State',       'Gwarinpa',
         'Kabusa', 'Lugbe District',   'Apo District',     'Osun State',
   'Rivers State',  'Port-Harcourt',      'Imo State',          'Bwari',
     'Abia State',        'Garki 1',          'Ojota',    'Ekiti State',
         'Gwagwa',         'Sagamu',           'Jiwa',           'Wuse']
Length: 28, dtype: str

In [21]:
new_df['Region Parent Name'] = new_df['Region Parent Name'].replace(['Lugbe District', 'Katampe', 'Apo District','Wuse',
                                                                     'Gwagwa', 'Gwarinpa', 'Garki 1', 'Jiwa', 'Bwari',  ], 'Abuja (FCT)')

new_df['Region Parent Name'].unique()

<ArrowStringArray>
[  'Lagos State',   'Enugu State',   'Abuja (FCT)',    'Ogun State',
          'Yaba',     'Oyo State',        'Ibadan',   'Kwara State',
           'Oyo',     'Edo State',        'Kabusa',    'Osun State',
  'Rivers State', 'Port-Harcourt',     'Imo State',    'Abia State',
         'Ojota',   'Ekiti State',        'Sagamu']
Length: 19, dtype: str

In [22]:
new_df['Region Parent Name'] = new_df['Region Parent Name'].replace(['Ibadan'], 'Oyo State')


new_df['Region Parent Name'].unique()

<ArrowStringArray>
[  'Lagos State',   'Enugu State',   'Abuja (FCT)',    'Ogun State',
          'Yaba',     'Oyo State',   'Kwara State',           'Oyo',
     'Edo State',        'Kabusa',    'Osun State',  'Rivers State',
 'Port-Harcourt',     'Imo State',    'Abia State',         'Ojota',
   'Ekiti State',        'Sagamu']
Length: 18, dtype: str

In [23]:
new_df['Region Parent Name'] = new_df['Region Parent Name'].replace(['Sagamu'], 'Ogun State')

new_df['Region Parent Name'].unique()

<ArrowStringArray>
[  'Lagos State',   'Enugu State',   'Abuja (FCT)',    'Ogun State',
          'Yaba',     'Oyo State',   'Kwara State',           'Oyo',
     'Edo State',        'Kabusa',    'Osun State',  'Rivers State',
 'Port-Harcourt',     'Imo State',    'Abia State',         'Ojota',
   'Ekiti State']
Length: 17, dtype: str

In [24]:
new_df["Is Boost"].unique()

<ArrowStringArray>
['premium', 'diamond', 'vip_gold', 'False', 'enterprise', 'basic', 'vip']
Length: 7, dtype: str

In [25]:
new_df['Is Boost'] = new_df['Is Boost'].replace({
    'premium' : 'Premium', 
    'enterprise' : 'Enterprise', 
    'diamond' : 'Diamond', 
    'vip_gold' : 'VIP Gold',
    'vip' : 'VIP',
    'basic' : 'Basic'
} )

new_df['Is Boost'].unique()

<ArrowStringArray>
['Premium', 'Diamond', 'VIP Gold', 'False', 'Enterprise', 'Basic', 'VIP']
Length: 7, dtype: str

In [26]:
# Question: Remove duplicates;Look for duplicate titles or identical rows.
new_df.drop_duplicates(inplace=True)
new_df

,Title,Property Size,Bedrooms,Bathrooms,Furnishing,Region,Region Name,Region Parent Name,Is Boost,Price
0,"3bdrm Bungalow in Greenleaf Estate, Ebute for ...",300.00,3,4,Unfurnished,"Ikorodu, Ebute",Ebute,Lagos State,Premium,43000000.00
1,Furnished 4bdrm Duplex in Enugu for sale,1000.00,4,4,Furnished,"Enugu State, Enugu",Enugu,Enugu State,Premium,350000000.00
2,"5bdrm Duplex in Basic Estate, Lokogoma for sale",600.00,5,4,Unfurnished,"Abuja (FCT), Lokogoma",Lokogoma,Abuja (FCT),Diamond,220000000.00
3,2bdrm Apartment in Lekki Phase 1 for sale,300.00,2,2,semi-furnished,"Lekki, Lekki Phase 1",Lekki Phase 1,Lagos State,VIP Gold,350000000.00
4,2bdrm Bungalow in Ewekoro for sale,600.00,2,2,Unfurnished,"Ogun State, Ewekoro",Ewekoro,Ogun State,False,7000000.00
...,...,...,...,...,...,...,...,...,...,...
1993,5bdrm Duplex in Zone 7 / Wuse for sale,300.00,5,6,semi-furnished,"Wuse, Zone 7 / Wuse",Zone 7 / Wuse,Abuja (FCT),Diamond,750000000.00
1995,4bdrm Duplex in Gaduwa for sale,400.00,4,6,semi-furnished,"Abuja (FCT), Gaduwa",Gaduwa,Abuja (FCT),Diamond,250000000.00
1996,6bdrm Bungalow in New London Estate for sale,620.00,6,6,Unfurnished,"Ipaja, Baruwa",Baruwa,Lagos State,Diamond,65000000.00
1997,4bdrm Duplex in Wuye for sale,150.00,4,5,semi-furnished,"Abuja (FCT), Wuye",Wuye,Abuja (FCT),Diamond,500000000.00
1998,4bdrm Duplex in Jahi for sale,250.00,4,5,Unfurnished,"Abuja (FCT), Jahi",Jahi,Abuja (FCT),Diamond,250000000.00

In [27]:
new_df.info()

<class 'pandas.DataFrame'>
Index: 1731 entries, 0 to 1998
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               1731 non-null   str
 1   Property Size       1731 non-null   float64
 2   Bedrooms            1731 non-null   int64
 3   Bathrooms           1731 non-null   int64
 4   Furnishing          1731 non-null   str
 5   Region              1731 non-null   str
 6   Region Name         1731 non-null   str
 7   Region Parent Name  1731 non-null   str
 8   Is Boost            1731 non-null   str
 9   Price               1731 non-null   float64
dtypes: float64(2), int64(2), str(6)
memory usage: 322.7 KB

In [28]:
new_df.isnull().sum()

Title                 0
Property Size         0
Bedrooms              0
Bathrooms             0
Furnishing            0
Region                0
Region Name           0
Region Parent Name    0
Is Boost              0
Price                 0
dtype: int64

In [29]:
# Question: Save cleaned dataset as:  jiji_housing_cleaned.csv

new_df.to_csv("data/jiji_housing_cleaned.csv", index=False)

In [30]:
#Task 3: Exploratory Data Analysis (EDA)
# 1. Price Analysis
#Question: What is the average house price in Nigeria?

avg_house_price = round(new_df["Price"].mean(), 2)


print(f"Average House Price:", avg_house_price)

Average House Price: 325159210.57

In [31]:
#Question: Which state has the highest and lowest mean property price?

state_property_price = (
    new_df.groupby("Region Parent Name")["Price"]
    .mean()
    .sort_values(ascending=False)
)
print("State With Highest Mean Property Price:")
print(state_property_price.head())

print("\nState With Lowest Mean Property Price:")
print(state_property_price.tail())

State With Highest Mean Property Price:
Region Parent Name
Ojota           550000000.00
Abuja (FCT)     357327819.55
Lagos State     354621710.59
Yaba            350000000.00
Port-Harcourt   260108474.58
Name: Price, dtype: float64

State With Lowest Mean Property Price:
Region Parent Name
Kwara State   56000000.00
Kabusa        48500000.00
Ekiti State   48500000.00
Oyo           45000000.00
Ogun State    41990476.19
Name: Price, dtype: float64

In [32]:
# 2. Property Size & Features
# Question: What is the distribution of property sizes?

new_df["Property Size"].value_counts().head(10)

Property Size
500.00     169
300.00     145
600.00     137
400.00     118
1000.00     92
250.00      75
450.00      73
350.00      67
100.00      63
50.00       55
Name: count, dtype: int64

In [41]:
## Question: Do houses with more bedrooms cost significantly more?
bedroom_cost = new_df.groupby("Bedrooms")["Price"].mean().value_counts()

print(bedroom_cost.head(10))

Price
300000000.00    2
100888461.54    1
190676229.51    1
217420008.01    1
303857770.80    1
485164414.41    1
446520000.00    1
373529411.76    1
207363636.36    1
419500000.00    1
Name: count, dtype: int64

In [43]:
## Question: Do houses with more bathrooms cost significantly more?
bathrooms_cost = new_df.groupby("Bathrooms")["Price"].mean().value_counts()

print(bathrooms_cost.head(10))

Price
300000000.00    2
332027272.73    1
201146296.30    1
228299783.02    1
290288336.35    1
429427672.95    1
443880620.16    1
395916666.67    1
298640000.00    1
352833333.33    1
Name: count, dtype: int64

In [34]:
# 4. Furnishing Analysis
# Question: Are furnished apartments more expensive on average?

furnishing_aprt = (
    new_df.groupby("Furnishing")["Price"]
    .mean()
    .sort_values(ascending=False)
)

print(furnishing_aprt)

Furnishing
Furnished        391305520.27
semi-furnished   327096895.15
Unfurnished      295050413.71
Name: Price, dtype: float64

In [35]:
# 5. Listing Type
# Do boosted/enterprise listings have higher prices?
boost_price = (
    new_df.groupby("Is Boost")["Price"]
    .mean().sort_values(ascending=False)
)

print(boost_price)

Is Boost
Basic        390289473.68
Enterprise   345855030.24
Diamond      319301326.16
VIP Gold     314704225.35
False        299474612.40
Premium      240214285.71
VIP          109023809.52
Name: Price, dtype: float64

In [36]:
#Correlation Analysis
corr = new_df[
    [
        "Price",
        "Property Size",
        "Bedrooms",
        "Bathrooms"
    ]
].corr()

corr

               Price  Property Size  Bedrooms  Bathrooms
Price           1.00           0.05      0.26       0.19
Property Size   0.05           1.00      0.06      -0.01
Bedrooms        0.26           0.06      1.00       0.85
Bathrooms       0.19          -0.01      0.85       1.00

In [37]:
new_df.to_csv("data/cleaned_nigeria_housing_dataset.csv", index=False)

Task 5: Summary of Findings Rewrite your findings by answering the following: Which states have the highest-priced listings?

Question 1: Which states have the highest-priced listings? 
Answer: Jigawa recorded the highest average property prices, followed closely by Lagos and Abuja

Question 2: Which states are the most affordable?
Answer: States in the North-Central and South-East regions generally showed lower average property prices.

Question 3: Do furnished homes consistently cost more than unfurnished ones?
Answer: Furnished properties consistently sold at higher prices than unfurnished properties.

Question 4: How strongly do bedrooms, bathrooms, or property size influence price?
Answer: Bedrooms and bathrooms or property size shows a positive relationship with property price. Larger properties attracted premium pricing across all regions.

Question 5: Are boosted (Enterprise) listings typically more expensive?
Answer: Yes, Enterprise/boosted listings were typically more expensive than other listings.

Question 6: What property types attract premium pricing?
Answer: Lagos dominated listing volume while Abuja dominated luxury property sales.

Question 7: What patterns exist in Lagos vs Abuja vs other regions?
Answer: Most affordable properties were concentrated in other regional markets outside Lagos and Abuja

Task 6: Business Insights & Recommendations Provide a 5–7 line business-focused insight summary, answering: Which housing type or feature performs best overall on Jiji?

Question 1: Which housing type or feature performs best overall on jiji?
Answer: Luxury apartments with multiple bedrooms and modern furnishing generate the highest market value on Jiji.

Question 2: Which state contributes the most revenue potential?
Answer: Lagos contributes the greatest revenue potential due to its high listing volume and premium pricing.

Question 3: Which states underperform?
Answer: Ekiti State, Kwara State and Akwa Ibom State were the underperforming states

Question 4: Which period (if using timestamps) records the highest listing activity?

Question 5: What strategies can improve sales in low-performing regions?
Answer: Sellers should invest in professional photos, detailed descriptions, and boosted listings to improve visibility.
Jiji can increase activity in underperforming states through targeted advertising and regional promotions.

Question 6: What can sellers do to increase listing visibility and pricing power?
Answer: Real-estate agents in low-performing regions should emphasize affordability and financing options